[window]
opacity = 0.92
decorations = "buttonless"
blur = false
startup_mode = "Maximized"
dynamic_title = true
option_as_alt = "Both"
padding = { x = 3, y = 0 }

[colors.bright]
black = "#555555"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff6666"
white = "#ffffff"
yellow = "#f1fa8c"

[colors.normal]
black = "#000000"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff6666"
white = "#bbbbbb"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
#cursor = "#bbbbbb"
foreground = "#efefef"

[cursor.style]
blinking = "Never"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "MesloLGL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGL Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font Mono"
style = "Regular"

[env]
term = "xterm-256color"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
# CMD+Backspace: Delete entire line
key = "Back"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
# ALT+Backspace: Delete word backward
key = "Back"
mods = "Alt"
chars = "\u0017"

[[keyboard.bindings]]
# CMD+Left: Move to beginning of line
key = "Left"
mods = "Command"
chars = "\u0001"

[[keyboard.bindings]]
# CMD+Right: Move to end of line
key = "Right"
mods = "Command"
chars = "\u0005"

[[keyboard.bindings]]
# ALT+Left: Move backward by word
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
# ALT+Right: Move forward by word
key = "Right"
mods = "Alt"
chars = "\u001bf"

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
